version: '3.7'


services:
  agent-eta-form:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - .:/var/www/:rw,consistent
    container_name: spia-agent-eta-form
    env_file: .env
